sudo: false
language: node_js
node_js:
- '10'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
  - npm install -g @lhci/cli@0.3.x
install:
  - npm install
script:
  - npm run build
  - lhci autorun
addons:
  chrome: stable
notifications:
  email:
    - khacks@karunya.edu.in
