sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
install:
  - npm install
script:
  - npm run build
  - ./scripts/lighthouse.sh
addons:
  chrome: stable
notifications:
  email:
    - khacks@karunya.edu.in
